import React, { useEffect } from "react";
import styles from "./SignInModal.module.css";
import Modal from "react-modal";
import CheckedCircle from "./CheckedCircle";
import CustomConnectButton from "../TopBar/SignInButton/CustomConnectButton";
import { useAccount } from "wagmi";
Modal.setAppElement("*");
const SignInModal = ({
  onRequestClose,
  isOpen,
  onSignInComplete,
  onSignIn,
}) => {
  const customStyles = {
    content: {
      background:
        "linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.8) 41.15%)",
      height: "fit-content",
      width: "fit-content",
      margin: "auto",
      backdropFilter: "blur(60px)",
      borderRadius: "16px",
      borderColor: "#000000",
      padding: "0px",
    },
    overlay: {
      background: "rgba(0, 0, 0, 0.6)",
    },
  };

  const { isConnected } = useAccount();

  useEffect(() => {
    if (isConnected) {
      onSignIn();
    }

    return () => {};
  }, [isConnected]);

  return (
    <Modal onRequestClose={onRequestClose} isOpen={isOpen} style={customStyles}>
      <div
        className={`flex flex-col justify-start items-start rounded-[16px] backdrop-blur-3xl  ${styles.ModalContainer}`}
      >
        <CustomConnectButton onSignInComplete={onSignInComplete} />
        <div
          className={`flex justify-start flex-col gap-[12px] not-italic text-[12px] font-medium ${styles.LensInfo}`}
        >
          <div className="flex gap-[8px] justify-start items-center">
            <CheckedCircle />
            Checkout NFTs by Lens Frens
          </div>
          <div className="flex gap-[8px] justify-start items-center">
            <CheckedCircle />
            Submit NFTs generated by you
          </div>
          <div className="flex gap-[8px] justify-start items-center">
            <CheckedCircle />
            Collect other NFTs
          </div>
          <div className="flex justify-start items-center text-[13px] leading-[160%] font-medium text-[rgba(255, 255, 255, 0.8)]">
            New to Lens?
            <span
              className="underline ml-2 text-[#ADFF00]"
              onClick={() => {
                window.open("https://claim.lens.xyz/", "_blank");
              }}
            >
              Create an account
            </span>
          </div>
        </div>
      </div>
    </Modal>
  );
};

export default SignInModal;
