import React, { useEffect, useRef, useState } from "react";
import styles from "./CustomSignInModal.module.scss";
import Modal from "react-modal";
import SignInButton from "../TopBar/SignInButton";
import CheckedCircle from "../SignInModal/CheckedCircle";
import { useAccount } from "wagmi";
import CustomConnectButton from "../TopBar/SignInButton/CustomConnectButton";
import FireSmallSvg from "../vote/svg/FirstTimeUser/FireSmallSvg";
Modal.setAppElement("*");
const CustomSignInModal = ({ onRequestClose, isOpen, pageInfo, onSuccess }) => {
  const { isConnected } = useAccount();
  const [shouldCallSignInMethod, setShouldCallSignInMethopd] = useState(false);
  const isPreviouslyConnected = useRef(isConnected);

  const customStyles = {
    content: {
      background:
        "linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.8) 41.15%)",
      height: "fit-content",
      width: "fit-content",
      margin: "auto",
      backdropFilter: "blur(60px)",
      borderRadius: "16px",
      borderColor: "#000000",
      padding: "0px",
    },
    overlay: {
      background: "rgba(0, 0, 0, 0.6)",
    },
  };

  useEffect(() => {
    if (isPreviouslyConnected.current === false && isConnected === true) {
      isPreviouslyConnected.current = true;
      setShouldCallSignInMethopd(true);
    }
  }, [isConnected]);

  // console.log({
  //   c: isPreviouslyConnected.current === false && isConnected === true,
  //   isConnected: isConnected,
  //   shouldCallSignInMethod,
  // });

  return (
    <Modal onRequestClose={onRequestClose} isOpen={isOpen} style={customStyles}>
      <div
        className={`flex flex-col justify-center items-center rounded-[16px] backdrop-blur-3xl  ${styles.ModalContainer}`}
      >
        {!isConnected ? (
          <CustomConnectButton />
        ) : (
          <SignInButton
            showSquareLoginButton={true}
            onSuccess={() => {
              onRequestClose();
              if (onSuccess) onSuccess();
            }}
            isSignInModalOpen={isOpen}
            key={isConnected}
            isWalletConnected={shouldCallSignInMethod}
            onRejection={onRequestClose}
          />
        )}
        <div className="flex gap-[4px]">
          <span className="text-white opacity-60 not-italic text-[12px] font-medium">
            on
          </span>
          <span className="text-white opacity-80 not-italic text-[12px] font-medium">
            testnet
          </span>
        </div>

        {pageInfo === "votePage" && (
          <div className="flex relative mb-[13px] justify-center gap-[4px] items-center text-[12px] leading-[160%] font-medium text-white/60">
            and
            <span className="flex justify-center items-center text-[12px] leading-[160%] font-medium text-white/80 ">
              save your <FireSmallSvg height={18} width={16} /> votes now
            </span>
          </div>
        )}
        <div
          className={`flex justify-start flex-col gap-[12px] not-italic text-[12px] font-medium ${styles.LensInfo}`}
        >
          <div className="flex gap-[8px] justify-start items-center">
            <CheckedCircle />
            Checkout NFTs by Lens Frens
          </div>
          <div className="flex gap-[8px] justify-start items-center">
            <CheckedCircle />
            Submit NFTs generated by you
          </div>
          <div className="flex gap-[8px] justify-start items-center">
            <CheckedCircle />
            Collect other NFTs
          </div>
          <div className="flex justify-start items-center text-[13px] leading-[160%] font-medium text-white/80">
            New to Lens?
            <span
              className="underline cursor-pointer ml-2 text-[#ADFF00]"
              onClick={() => {
                window.open("https://claim.lens.xyz/", "_blank");
              }}
            >
              Create an account
            </span>
          </div>
        </div>
        {pageInfo === "votePage" && (
          <div className="flex flex-col justify-center gap-[4px] items-center text-[12px] leading-[160%] font-medium text-white/60">
            or
            <span
              className="flex hover:underline justify-center items-center text-[12px] leading-[160%] font-medium text-white/80 cursor-pointer"
              onClick={onRequestClose}
            >
              Continue without signing in
            </span>
          </div>
        )}
      </div>
    </Modal>
  );
};

export default CustomSignInModal;
