replicaCount: 1
 
fullnameOverride: "nftornot-frontend"
 
service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  className: nginx
  tls:
    - hosts:
      - nftornot.com
      secretName: nftornot.com
  hosts:
    - host: nftornot.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80